name: "Check"
on:
  pull_request:
  workflow_dispatch:
jobs:
  # From: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
  # NOTE: this action would be run only when the Dockerfile has changed
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          # TODO: provide proper context
          context: .
          file: ./docker/base/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  check-everything:
    name: Check everything
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
      - name: Run checks
        uses: addnab/docker-run-action@v3
        with:
          # This is an image that is on dockerhub
          image: trustworthysystems/rust-sel4-sel4cp-demo
          options: -v ${{ github.workspace }}:/work
          run: make test BUILD=/tmp/build
